name: $(semanticVersion)-build$(rev:rrr)

trigger:
  - main

pool: default

variables:
  buildArtifactStaging: "$(Build.ArtifactStagingDirectory)"

steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo  'Default Working Directory: $(System.DefaultWorkingDirectory)'
        echo  'Pipeline Workspace: $(Pipeline.Workspace)'
        dir
    displayName: Show working directory

  - task: NodeTool@0
    inputs:
      versionSpec: "22.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "Install dependencies"

  - script: |
      cargo test
    displayName: "Run cargo tests"
    workingDirectory: src-tauri

  - script: |
      npm run tauri build
    displayName: "Build for production"

  # Artifacts produced requires the end user to have Microsoft Edge WebView2 installed
  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(buildArtifactStaging)"
      Contents: "src-tauri/target/release/disk-analyzer.exe"
      TargetFolder: drop
    displayName: "Copy files to drop folder"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: drop
